version: '3'
services:
    mongodb:
        image: mongo:4.2-bionic
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: r00t
        volumes:
            - $HOME/apps/mongo/data:/data/db
        restart: always
