version: '3'
services:
  es:
   image: elasticsearch:7.8.1
   container_name: es
   environment:
     - discovery.type=single-node
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
     - TAKE_FILE_OWNERSHIP=true
   ports:
     - 9200:9200
   volumes:
     - /opt/cavitos/elasticsearch/data:/usr/share/elasticsearch/data
     - /opt/cavitos/elasticsearch/logs:/usr/share/elasticsearch/logs
